### ISSUE TITLE
Error: key $clusterTime must not start with '$'

### ISSUE THREAD

**Issue by romcok** [VeliovGroup/Meteor-Files-Demos#13]
Hi, I have problem with /demo. When I am trying to upload file I get error message "Can't start 500".
Here is log from console:
```
I20181201-15:22:15.411(1)? [FilesCollection] [File Start Method] [EXCEPTION:] mov_bbb.mp4 - iYvNKYCo4XiK6ZoR6 Error: key $clusterTime must not start with '$'
I20181201-15:22:15.411(1)?     at Query.toBin (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/commands.js:146:25)
I20181201-15:22:15.412(1)?     at serializeCommands (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:1045:43)
I20181201-15:22:15.412(1)?     at Pool.write (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:1261:3)
I20181201-15:22:15.412(1)?     at executeWrite (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:147:10)
I20181201-15:22:15.413(1)?     at WireProtocol.insert (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:158:3)
I20181201-15:22:15.413(1)?     at Server.insert (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/topologies/server.js:815:35)
I20181201-15:22:15.413(1)?     at Server.insert (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/topologies/topology_base.js:321:25)
I20181201-15:22:15.414(1)?     at OrderedBulkOperation.finalOptionsHandler (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:1003:25)
I20181201-15:22:15.414(1)?     at executeCommands (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/ordered.js:165:17)
I20181201-15:22:15.414(1)?     at executeOperation (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:420:24)
I20181201-15:22:15.414(1)?     at OrderedBulkOperation.execute (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/ordered.js:121:12)
I20181201-15:22:15.415(1)?     at bulkWrite (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/operations/collection_ops.js:115:8)
I20181201-15:22:15.415(1)?     at executeOperation (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:420:24)
I20181201-15:22:15.415(1)?     at Collection.insertMany (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:528:10)
I20181201-15:22:15.416(1)?     at Collection.insert (/Users/romcok/.meteor/packages/npm-mongo/.3.1.1.1m4dysf.ccgd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:675:15)
I20181201-15:22:15.416(1)?     at MongoConnection._insert (packages/mongo/mongo_driver.js:373:16)
I20181201-15:22:15.416(1)?     at MongoConnection.<anonymous> (packages/meteor.js:376:21)
I20181201-15:22:15.417(1)?     at MongoConnection.(anonymous function) [as insert] (packages/mongo/mongo_driver.js:754:49)
I20181201-15:22:15.417(1)?     at Collection.insert (packages/mongo/collection.js:520:39)
I20181201-15:22:15.418(1)?     at MethodInvocation.FilesCollection._methods.(anonymous function) (packages/ostrio:files/server.js:751:31)
I20181201-15:22:15.419(1)?     at currentArgumentChecker.withValue (packages/check/match.js:118:15)
I20181201-15:22:15.419(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20181201-15:22:15.498(1)? [FilesCollection] [Abort Method]: iYvNKYCo4XiK6ZoR6 -
I20181201-15:23:22.573(1)? [FilesCollection] [remove({"meta.expireAt":{"$lte":"2018-12-01T14:25:22.567Z"}})]
```

Someone know where is the problem? Other demos is working. Thanks

**Comment by dr-dimitru** [comment]
Hello @romcok ,

This is known issue:

1. https://jira.mongodb.org/browse/NODE-1627?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by dr-dimitru** [comment]
Hello @romcok ,

I've faced exact same issue in https://github.com/VeliovGroup/flow-router/issues/59
Solved with running my own local MongoDB instead of bundled with Meteor, it will be solved on the next release, due to [this MongoDB issue](https://jira.mongodb.org/browse/NODE-1627?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel), so bundled MongoDB simply needs to be updated.

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
